[program:laravel-worker]

process_name=%(program_name)s_%(process_num)02d

command=php /var/www/artisan queue:work redis --sleep=3 --tries=3 --timeout=90

autostart=true

autorestart=true

stopasgroup=true

killasgroup=true

user=www-data

numprocs=1

redirect_stderr=true

stdout_logfile=/var/www/storage/logs/worker.log

stopwaitsecs=3600
# Đối với Docker hiện đại:  app   worker   scheduler  là 3 container riêng.Mỗi container chỉ chạy một tiến trình.
# Với cấu trúc hiện tại của bạn, mình không khuyên bật Supervisor.
# Thay vào đó, giữ: command:       |    cho worker và scheduler là hợp lý. ở docker-compose.yml 
# Supervisor chỉ thực sự cần khi một container phải quản lý nhiều tiến trình.
# nếu muốn dùng Supervisor : docker-compose.yml  :   command: supervisord -n    |    Dockerfile kết thúc bằng: CMD ["supervisord","-n"]


# Nó làm gì?
# Ví dụ:
# Laravel có Job :
# SendEmailJob
# Controller > Dispatch Job > Redis > Queue > Supervisor > Worker > Gửi Email

# Nếu Queue bị lỗi :
# Ví dụ : 
# Segmentation fault
# Supervisor > Khởi động lại Worker. > Không cần bạn SSH vào server.

# Log : 
# stdout_logfile=/var/www/storage/logs/worker.log
# Sau này :
# storage/logs/
# laravel.log
# worker.log
# Bạn biết Queue đang làm gì.

# Dockerfile cần sửa
# Hiện tại Dockerfile của bạn đã cài Supervisor, nhưng chưa copy file cấu hình.
# Thêm:
# COPY docker/supervisor/laravel-worker.conf /etc/supervisor/conf.d/laravel-worker.conf